version: '3.8'

services:
  app:
    build:
      context: . 
    container_name: mi-laravel-app
    ports:
      - "8080:80" 
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=prueba_homeland
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - SESSION_DRIVER=array
      - QUEUE_CONNECTION=sync

  db:
    image: mysql:8.0
    container_name: mi-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prueba_homeland
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./insertimagenes.sql:/docker-entrypoint-initdb.d/insertimagenes.sql 
volumes:
  dbdata:
